"""
╔══════════════════════════════════════════════════════════╗
║      TARS — PowerPoint Generator (python-pptx)           ║
╠══════════════════════════════════════════════════════════╣
║  Generate professional .pptx presentations.              ║
║  Saves to ~/Documents/TARS_Reports/                      ║
╚══════════════════════════════════════════════════════════╝
"""

import os
import logging
from datetime import datetime

logger = logging.getLogger("tars.pptx_gen")

REPORT_DIR = os.path.expanduser("~/Documents/TARS_Reports")
os.makedirs(REPORT_DIR, exist_ok=True)


def generate_presentation(title, slides, subtitle=None, filename=None):
    """Generate a PowerPoint presentation.
    
    Args:
        title: Presentation title (first slide)
        slides: List of dicts, each with:
            - "title": Slide title (required)
            - "bullets": List of bullet point strings
            - "body": Body text (alternative to bullets)
            - "image_path": Optional image path
        subtitle: Optional subtitle on title slide
        filename: Custom filename (auto-generated if None)
    
    Returns:
        Standard tool result dict with path
    """
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt, Emu
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN
    except ImportError:
        return {
            "success": False, "error": True,
            "content": "python-pptx not installed. Run: pip install python-pptx"
        }

    try:
        prs = Presentation()
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)

        # ── Color scheme ──
        dark_bg = RGBColor(0x1A, 0x1A, 0x2E)
        accent = RGBColor(0x00, 0xD4, 0xFF)
        white = RGBColor(0xFF, 0xFF, 0xFF)
        light_gray = RGBColor(0xCC, 0xCC, 0xCC)

        # ── Title Slide ──
        slide_layout = prs.slide_layouts[6]  # Blank layout
        slide = prs.slides.add_slide(slide_layout)

        # Background
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = dark_bg

        # Title text
        from pptx.util import Inches, Pt
        txBox = slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(11), Inches(2))
        tf = txBox.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = title
        p.font.size = Pt(44)
        p.font.bold = True
        p.font.color.rgb = white
        p.alignment = PP_ALIGN.LEFT

        # Subtitle
        if subtitle:
            p2 = tf.add_paragraph()
            p2.text = subtitle
            p2.font.size = Pt(20)
            p2.font.color.rgb = light_gray
            p2.alignment = PP_ALIGN.LEFT

        # Date line
        p3 = tf.add_paragraph()
        p3.text = f"Generated by TARS · {datetime.now().strftime('%B %d, %Y')}"
        p3.font.size = Pt(14)
        p3.font.color.rgb = accent
        p3.alignment = PP_ALIGN.LEFT

        # ── Content Slides ──
        for slide_data in slides:
            slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank

            # Background
            background = slide.background
            fill = background.fill
            fill.solid()
            fill.fore_color.rgb = dark_bg

            # Slide title
            txBox = slide.shapes.add_textbox(Inches(0.8), Inches(0.5), Inches(11.5), Inches(1))
            tf = txBox.text_frame
            p = tf.paragraphs[0]
            p.text = slide_data.get("title", "")
            p.font.size = Pt(32)
            p.font.bold = True
            p.font.color.rgb = accent

            # Accent line
            from pptx.util import Emu
            line_shape = slide.shapes.add_shape(
                1,  # Rectangle
                Inches(0.8), Inches(1.5), Inches(2), Pt(3)
            )
            line_shape.fill.solid()
            line_shape.fill.fore_color.rgb = accent
            line_shape.line.fill.background()

            # Content
            content_top = Inches(1.8)
            content_box = slide.shapes.add_textbox(
                Inches(0.8), content_top, Inches(11.5), Inches(5)
            )
            ctf = content_box.text_frame
            ctf.word_wrap = True

            if slide_data.get("bullets"):
                for i, bullet in enumerate(slide_data["bullets"]):
                    if i == 0:
                        p = ctf.paragraphs[0]
                    else:
                        p = ctf.add_paragraph()
                    p.text = f"  •  {bullet}"
                    p.font.size = Pt(20)
                    p.font.color.rgb = white
                    p.space_after = Pt(12)

            elif slide_data.get("body"):
                p = ctf.paragraphs[0]
                p.text = slide_data["body"]
                p.font.size = Pt(18)
                p.font.color.rgb = white

            # Image
            if slide_data.get("image_path") and os.path.exists(slide_data["image_path"]):
                try:
                    slide.shapes.add_picture(
                        slide_data["image_path"],
                        Inches(7), Inches(2), width=Inches(5)
                    )
                except Exception as e:
                    logger.warning(f"Could not add image: {e}")

        # ── Save ──
        if not filename:
            safe_title = "".join(c if c.isalnum() or c in " _-" else "_" for c in title)
            filename = f"{safe_title}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pptx"

        filepath = os.path.join(REPORT_DIR, filename)
        prs.save(filepath)

        logger.info(f"Presentation generated: {filepath} ({len(slides)} slides)")
        return {
            "success": True,
            "path": filepath,
            "content": f"Presentation '{title}' saved to {filepath} ({len(slides)} content slides + title slide)"
        }

    except Exception as e:
        return {"success": False, "error": True, "content": f"PowerPoint generation error: {e}"}
